name: Build and deploy Node.js app to Azure Web App - app-002-gen10-step3-1-node-oshima51

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Prepare deploy source (exclude node_modules/.next)
        run: |
          mkdir -p deploy_src
          rsync -av --delete \
            --exclude=node_modules \
            --exclude=.next \
            --exclude=.git \
            --exclude='.github' \
            ./ deploy_src/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima51'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BB2BC5009E4444B2A2017505BC4D5ECC }}
